2019-08-24 10:20:14 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 10:22:00 ERROR [tasks.views:63] Project matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 59, in get_tasks_by_project
    project = Project.objects.get(name=name)        #noqa : Django Queryset
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
projects.models.Project.DoesNotExist: Project matching query does not exist.
2019-08-24 10:22:19 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 10:23:28 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 10:24:28 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 10:24:40 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 10:26:46 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 10:27:23 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-08-24 10:31:19 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-08-24 10:31:22 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-08-24 10:31:30 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-08-24 10:31:34 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-08-24 10:32:02 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-08-24 10:32:02 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-08-24 10:32:08 INFO [home.base_views:26] Parameters Receieved, PK - 5, Action - change
2019-08-24 10:32:13 INFO [home.base_views:75] Params Receieved - pk - 5, Action - change
2019-08-24 10:32:13 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-08-24 10:32:14 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-08-24 10:32:18 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-08-24 10:32:57 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-08-24 10:32:57 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-08-24 10:33:17 ERROR [tasks.views:63] Project matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 59, in get_tasks_by_project
    project = Project.objects.get(name=name)        #noqa : Django Queryset
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
projects.models.Project.DoesNotExist: Project matching query does not exist.
2019-08-24 10:39:31 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-08-24 10:39:32 INFO [home.base_views:26] Parameters Receieved, PK - 1, Action - change
2019-08-24 10:39:35 INFO [home.base_views:75] Params Receieved - pk - 1, Action - change
2019-08-24 10:39:35 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-08-24 11:13:55 ERROR [tasks.views:63] Project matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 59, in get_tasks_by_project
    project = Project.objects.get(name=name)        #noqa : Django Queryset
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
projects.models.Project.DoesNotExist: Project matching query does not exist.
2019-08-24 11:20:09 ERROR [tasks.views:63] Project matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 59, in get_tasks_by_project
    project = Project.objects.get(name=name)        #noqa : Django Queryset
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
projects.models.Project.DoesNotExist: Project matching query does not exist.
2019-08-24 11:20:58 ERROR [tasks.views:63] Project matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 59, in get_tasks_by_project
    project = Project.objects.get(name=name)        #noqa : Django Queryset
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
projects.models.Project.DoesNotExist: Project matching query does not exist.
2019-08-24 11:46:10 ERROR [tasks.views:118] Task matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 104, in browse
    obj = Task.objects.get(key=task_key)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
tasks.models.Task.DoesNotExist: Task matching query does not exist.
2019-08-24 11:46:22 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 17:04:06 ERROR [tasks.views:118] Task matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 104, in browse
    obj = Task.objects.get(key=task_key)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
tasks.models.Task.DoesNotExist: Task matching query does not exist.
2019-08-24 18:11:58 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 18:13:56 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 20:57:32 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 21:15:30 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 21:17:41 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 21:55:04 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 22:42:37 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 22:48:17 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 22:49:25 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 23:11:51 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 23:23:13 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 23:24:56 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 23:25:23 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 23:26:40 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 23:26:44 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 23:26:57 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-08-24 23:26:58 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-08-24 23:28:04 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 23:28:05 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 23:28:31 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 23:29:59 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 23:30:13 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 23:30:58 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 23:30:59 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 23:30:59 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 23:31:00 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 23:31:00 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 23:31:00 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 23:31:00 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 23:31:00 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-24 23:31:01 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-27 21:09:54 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-08-27 21:09:56 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-08 11:39:05 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-08 11:41:25 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-08 11:42:21 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:42:23 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-08 11:42:37 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:42:41 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:42:46 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:42:50 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:44:53 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:44:56 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:44:58 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:44:59 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:45:01 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:45:16 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:47:13 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:47:15 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:47:15 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:47:15 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:47:15 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:47:16 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:47:16 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:49:40 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:49:42 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:49:42 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:49:42 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:49:42 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:49:42 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:50:24 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:50:38 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:50:58 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:51:14 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:51:16 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:51:17 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:51:26 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-08 11:52:46 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 11:55:18 ERROR [tasks.views:63] Project matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 59, in get_tasks_by_project
    project = Project.objects.get(name=name)        #noqa : Django Queryset
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
projects.models.Project.DoesNotExist: Project matching query does not exist.
2019-09-08 12:17:20 INFO [tasks.views:151] Searching Tasks
2019-09-08 12:18:34 INFO [tasks.views:151] Searching Tasks
2019-09-08 12:18:34 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 12:19:14 INFO [tasks.views:151] Searching Tasks
2019-09-08 12:19:14 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 12:47:44 INFO [tasks.views:151] Searching Tasks
2019-09-08 12:47:44 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 14:45:18 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-08 14:49:06 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-08 14:49:09 INFO [tasks.views:151] Searching Tasks
2019-09-08 14:49:09 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 14:49:46 INFO [tasks.views:151] Searching Tasks
2019-09-08 14:49:50 INFO [tasks.views:151] Searching Tasks
2019-09-08 14:49:50 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 16:12:45 INFO [tasks.views:151] Searching Tasks
2019-09-08 16:12:45 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 16:14:27 INFO [tasks.views:151] Searching Tasks
2019-09-08 16:14:27 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 16:16:04 INFO [tasks.views:151] Searching Tasks
2019-09-08 16:16:04 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 16:16:05 INFO [tasks.views:151] Searching Tasks
2019-09-08 16:16:05 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 16:16:05 INFO [tasks.views:151] Searching Tasks
2019-09-08 16:16:05 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 16:16:05 INFO [tasks.views:151] Searching Tasks
2019-09-08 16:16:05 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 16:16:05 INFO [tasks.views:151] Searching Tasks
2019-09-08 16:16:05 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 16:16:28 INFO [tasks.views:151] Searching Tasks
2019-09-08 16:16:28 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 16:16:28 INFO [tasks.views:151] Searching Tasks
2019-09-08 16:16:28 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 16:16:28 INFO [tasks.views:151] Searching Tasks
2019-09-08 16:16:28 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 16:16:28 INFO [tasks.views:151] Searching Tasks
2019-09-08 16:16:28 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 16:16:28 INFO [tasks.views:151] Searching Tasks
2019-09-08 16:16:28 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 16:17:26 INFO [tasks.views:151] Searching Tasks
2019-09-08 16:17:26 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 16:17:46 INFO [tasks.views:151] Searching Tasks
2019-09-08 16:17:46 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 16:19:06 INFO [tasks.views:151] Searching Tasks
2019-09-08 16:19:06 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 16:20:26 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-08 16:22:54 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-08 16:22:58 INFO [tasks.views:151] Searching Tasks
2019-09-08 16:22:58 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 16:25:01 INFO [tasks.views:151] Searching Tasks
2019-09-08 16:25:01 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 16:28:49 INFO [tasks.views:151] Searching Tasks
2019-09-08 16:28:49 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 16:29:20 INFO [tasks.views:151] Searching Tasks
2019-09-08 16:29:20 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:37:25 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:37:25 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:43:36 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:43:36 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:43:40 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:43:40 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:43:41 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:43:41 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:45:41 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:45:41 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:45:44 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:45:44 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:51:45 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:51:45 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:51:46 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:51:46 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:52:40 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-08 22:52:44 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:52:44 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:55:19 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:55:19 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:55:41 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:55:41 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:55:57 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:55:57 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:56:12 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:56:12 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:56:28 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:56:28 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:57:05 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:57:05 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:58:06 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:58:06 ERROR [tasks.views:191] local variable 'project_list' referenced before assignment
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 187, in search
    "project_list": project_list
UnboundLocalError: local variable 'project_list' referenced before assignment
2019-09-08 22:58:10 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:58:10 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:58:23 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:58:23 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:58:59 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:58:59 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:59:14 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:59:14 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:59:21 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-08 22:59:27 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:59:27 ERROR [tasks.views:191] local variable 'project_list' referenced before assignment
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 187, in search
    "project_list": project_list
UnboundLocalError: local variable 'project_list' referenced before assignment
2019-09-08 22:59:30 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:59:30 ERROR [tasks.views:191] local variable 'project_list' referenced before assignment
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 187, in search
    "project_list": project_list
UnboundLocalError: local variable 'project_list' referenced before assignment
2019-09-08 22:59:31 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-08 22:59:35 INFO [tasks.views:151] Searching Tasks
2019-09-08 22:59:35 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 22:59:45 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-08 23:01:18 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 23:02:18 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 23:02:31 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-08 23:02:45 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 23:02:48 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-08 23:02:52 INFO [tasks.views:151] Searching Tasks
2019-09-08 23:02:52 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 23:02:54 INFO [tasks.views:151] Searching Tasks
2019-09-08 23:02:55 ERROR [tasks.views:191] local variable 'project_list' referenced before assignment
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 187, in search
    "project_list": project_list
UnboundLocalError: local variable 'project_list' referenced before assignment
2019-09-08 23:03:22 INFO [tasks.views:151] Searching Tasks
2019-09-08 23:03:22 ERROR [tasks.views:191] local variable 'project_list' referenced before assignment
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 187, in search
    "project_list": project_list
UnboundLocalError: local variable 'project_list' referenced before assignment
2019-09-08 23:03:23 INFO [tasks.views:151] Searching Tasks
2019-09-08 23:03:23 ERROR [tasks.views:191] local variable 'project_list' referenced before assignment
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 187, in search
    "project_list": project_list
UnboundLocalError: local variable 'project_list' referenced before assignment
2019-09-08 23:03:27 INFO [tasks.views:151] Searching Tasks
2019-09-08 23:03:27 INFO [tasks.views:177] Fetching All Tasks.
2019-09-08 23:12:15 INFO [tasks.views:154] Searching Tasks
2019-09-08 23:12:15 INFO [tasks.views:180] Fetching All Tasks.
2019-09-08 23:12:15 ERROR [tasks.views:205] Cannot resolve keyword 'username' into field. Choices are: created_at, created_by, created_by_id, description, id, modified_at, modified_by, modified_by_id, name, task, workflow, workflow_id
Traceback (most recent call last):
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1768, in add_fields
    join_info = self.setup_joins(name.split(LOOKUP_SEP), opts, alias, allow_many=allow_m2m)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1504, in setup_joins
    names[:pivot], opts, allow_many, fail_on_missing=True,
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1420, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'username' into field. Choices are: created_at, created_by, created_by_id, description, id, modified_at, modified_by, modified_by_id, name, task, workflow, workflow_id

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 185, in search
    user_list = list(TaskType.objects.all().values_list('username', flat=True))
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 825, in values_list
    clone = self._values(*_fields, **expressions)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 793, in _values
    clone.query.set_values(fields)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 2020, in set_values
    self.add_fields(field_names, True)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1791, in add_fields
    "Choices are: %s" % (name, ", ".join(names)))
django.core.exceptions.FieldError: Cannot resolve keyword 'username' into field. Choices are: created_at, created_by, created_by_id, description, id, modified_at, modified_by, modified_by_id, name, task, workflow, workflow_id
2019-09-08 23:13:18 INFO [tasks.views:154] Searching Tasks
2019-09-08 23:13:35 INFO [tasks.views:154] Searching Tasks
2019-09-08 23:13:37 INFO [tasks.views:154] Searching Tasks
2019-09-08 23:13:37 INFO [tasks.views:180] Fetching All Tasks.
2019-09-08 23:14:58 INFO [tasks.views:154] Searching Tasks
2019-09-08 23:14:58 INFO [tasks.views:180] Fetching All Tasks.
2019-09-08 23:19:58 INFO [tasks.views:154] Searching Tasks
2019-09-08 23:19:58 INFO [tasks.views:180] Fetching All Tasks.
2019-09-09 15:25:48 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-09 15:25:51 INFO [tasks.views:154] Searching Tasks
2019-09-09 15:25:51 INFO [tasks.views:180] Fetching All Tasks.
2019-09-09 15:26:05 INFO [tasks.views:154] Searching Tasks
2019-09-09 15:26:05 INFO [tasks.views:180] Fetching All Tasks.
2019-09-09 15:36:13 INFO [tasks.views:154] Searching Tasks
2019-09-09 15:36:13 INFO [tasks.views:180] Fetching All Tasks.
2019-09-09 21:24:56 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-09 21:30:39 INFO [tasks.views:154] Searching Tasks
2019-09-09 21:30:39 INFO [tasks.views:180] Fetching All Tasks.
2019-09-09 21:44:52 ERROR [tasks.views:238] Unable to find parent - FP-1
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 235, in post
    TaskDependency.objects.create(dependency_type="subtask", task=parent, dependent_task=key)
UnboundLocalError: local variable 'key' referenced before assignment
2019-09-09 22:05:35 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-09 22:15:32 ERROR [tasks.views:235] Task matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 232, in post
    t=Task.objects.get(key=parent)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
tasks.models.Task.DoesNotExist: Task matching query does not exist.
2019-09-09 22:16:52 ERROR [tasks.views:236] Task matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 233, in post
    t=Task.objects.get(key=parent)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
tasks.models.Task.DoesNotExist: Task matching query does not exist.
2019-09-09 22:50:46 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-09 22:50:58 INFO [tasks.views:170] Searching Tasks
2019-09-09 22:50:59 ERROR [tasks.views:147] Cannot resolve keyword 'dependency_type' into field. Choices are: created_at, created_by, created_by_id, id, inward, modified_at, modified_by, modified_by_id, name, outward
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 122, in browse
    childs = TaskDependency.objects.filter(task=obj, dependency_type="subtask")
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1190, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1049, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1420, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'dependency_type' into field. Choices are: created_at, created_by, created_by_id, id, inward, modified_at, modified_by, modified_by_id, name, outward
2019-09-09 22:51:05 ERROR [tasks.views:147] Cannot resolve keyword 'dependency_type' into field. Choices are: created_at, created_by, created_by_id, id, inward, modified_at, modified_by, modified_by_id, name, outward
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 122, in browse
    childs = TaskDependency.objects.filter(task=obj, dependency_type="subtask")
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1190, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1049, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1420, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'dependency_type' into field. Choices are: created_at, created_by, created_by_id, id, inward, modified_at, modified_by, modified_by_id, name, outward
2019-09-09 22:51:15 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-09 22:51:17 ERROR [tasks.views:147] Cannot resolve keyword 'dependency_type' into field. Choices are: created_at, created_by, created_by_id, id, inward, modified_at, modified_by, modified_by_id, name, outward
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 122, in browse
    childs = TaskDependency.objects.filter(task=obj, dependency_type="subtask")
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1190, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1049, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1420, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'dependency_type' into field. Choices are: created_at, created_by, created_by_id, id, inward, modified_at, modified_by, modified_by_id, name, outward
2019-09-09 22:55:27 INFO [tasks.views:170] Searching Tasks
2019-09-09 22:57:40 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-09 22:58:36 INFO [tasks.views:170] Searching Tasks
2019-09-09 22:59:51 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-09 23:06:08 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-09 23:12:03 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-09 23:13:03 INFO [tasks.views:168] Searching Tasks
2019-09-09 23:21:16 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-09 23:23:28 INFO [tasks.views:169] Searching Tasks
2019-09-09 23:25:18 INFO [tasks.views:169] Searching Tasks
2019-09-09 23:42:42 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:42:45 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-09 23:43:11 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-09 23:43:11 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:43:17 INFO [home.base_views:26] Parameters Receieved, PK - 1, Action - change
2019-09-09 23:43:19 INFO [home.base_views:75] Params Receieved - pk - 1, Action - change
2019-09-09 23:43:19 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:43:53 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:43:54 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:43:55 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:43:56 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:43:57 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:43:57 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:43:59 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:44:01 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:44:03 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:44:04 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:44:08 INFO [tasks.views:175] Searching Tasks
2019-09-09 23:44:08 INFO [tasks.views:201] Fetching All Tasks.
2019-09-09 23:44:15 INFO [tasks.views:175] Searching Tasks
2019-09-09 23:51:30 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-09 23:51:35 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:51:38 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-09 23:51:50 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-09 23:51:50 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:52:41 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:52:45 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-09 23:53:26 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-09 23:53:26 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:53:29 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:53:32 INFO [home.base_views:26] Parameters Receieved, PK - 1, Action - change
2019-09-09 23:53:36 INFO [home.base_views:75] Params Receieved - pk - 1, Action - change
2019-09-09 23:53:36 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:53:37 INFO [home.base_views:26] Parameters Receieved, PK - 1, Action - change
2019-09-09 23:53:39 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:53:42 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-09 23:54:06 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-09 23:54:06 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:54:08 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-09 23:54:30 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-09 23:54:30 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:54:32 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-09 23:54:54 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-09 23:54:54 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:54:56 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:54:57 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-09 23:55:15 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:55:17 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-09 23:56:22 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-09 23:56:22 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:56:24 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-09 23:56:44 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-09 23:56:44 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:56:47 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-09 23:57:05 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-09 23:57:05 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:57:07 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-09 23:57:23 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-09 23:57:23 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:57:24 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-09 23:57:45 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-09 23:57:46 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:57:49 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:57:52 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-09 23:58:17 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-09 23:58:17 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:58:19 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-09 23:58:49 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-09 23:58:49 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:59:15 INFO [home.base_views:26] Parameters Receieved, PK - 1, Action - change
2019-09-09 23:59:30 INFO [home.base_views:75] Params Receieved - pk - 1, Action - change
2019-09-09 23:59:30 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:59:32 INFO [home.base_views:26] Parameters Receieved, PK - 2, Action - change
2019-09-09 23:59:48 INFO [home.base_views:75] Params Receieved - pk - 2, Action - change
2019-09-09 23:59:48 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:59:50 INFO [home.base_views:26] Parameters Receieved, PK - 1, Action - change
2019-09-09 23:59:55 INFO [home.base_views:75] Params Receieved - pk - 1, Action - change
2019-09-09 23:59:55 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-09 23:59:59 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-10 00:00:36 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-10 00:00:36 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:00:38 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:00:40 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-10 00:01:02 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-10 00:01:48 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-10 00:03:54 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-10 00:03:54 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:03:56 INFO [home.base_views:26] Parameters Receieved, PK - 1, Action - change
2019-09-10 00:04:04 INFO [home.base_views:75] Params Receieved - pk - 1, Action - change
2019-09-10 00:04:04 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:04:05 INFO [home.base_views:26] Parameters Receieved, PK - 1, Action - change
2019-09-10 00:04:09 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:04:12 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-10 00:04:25 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-10 00:04:25 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:04:29 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-10 00:04:48 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-10 00:04:48 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:04:49 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-10 00:05:10 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-10 00:05:10 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:05:12 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:05:13 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:05:14 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:05:17 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:05:19 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:05:21 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:05:22 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:05:22 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:05:51 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-10 00:06:41 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-10 00:06:41 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:06:44 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-10 00:07:28 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-10 00:07:28 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:07:33 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:07:40 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:07:44 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-10 00:07:47 INFO [tasks.views:175] Searching Tasks
2019-09-10 00:07:50 INFO [tasks.views:175] Searching Tasks
2019-09-10 00:09:44 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-10 00:10:09 ERROR [tasks.models:64] list index out of range
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/models.py", line 62, in _get_initial_transition_state
    return self.tasktype.get_avilable_transitions("Create")[0]
IndexError: list index out of range
2019-09-10 00:10:09 ERROR [tasks.views:152] invalid literal for int() with base 10: 'subtask'
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 127, in browse
    subtasks = TaskDependencyMapping.objects.filter(task=obj, dependency_type="subtask")
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1116, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'subtask'
2019-09-10 00:10:36 ERROR [tasks.views:152] invalid literal for int() with base 10: 'subtask'
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 127, in browse
    subtasks = TaskDependencyMapping.objects.filter(task=obj, dependency_type="subtask")
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1116, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'subtask'
2019-09-10 00:10:36 ERROR [tasks.views:152] invalid literal for int() with base 10: 'subtask'
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 127, in browse
    subtasks = TaskDependencyMapping.objects.filter(task=obj, dependency_type="subtask")
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1116, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'subtask'
2019-09-10 00:10:38 ERROR [tasks.views:152] invalid literal for int() with base 10: 'subtask'
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 127, in browse
    subtasks = TaskDependencyMapping.objects.filter(task=obj, dependency_type="subtask")
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1116, in build_lookup
    lookup = lookup_class(lhs, rhs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/lookups.py", line 20, in __init__
    self.rhs = self.get_prep_lookup()
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/fields/related_lookups.py", line 115, in get_prep_lookup
    self.rhs = target_field.get_prep_value(self.rhs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/fields/__init__.py", line 966, in get_prep_value
    return int(value)
ValueError: invalid literal for int() with base 10: 'subtask'
2019-09-10 00:12:37 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:12:50 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:12:51 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:12:55 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-10 00:13:29 INFO [home.base_views:75] Params Receieved - pk - None, Action - add
2019-09-10 00:13:29 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:13:32 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:13:33 INFO [home.base_views:26] Parameters Receieved, PK - 1, Action - change
2019-09-10 00:13:38 INFO [home.base_views:75] Params Receieved - pk - 1, Action - change
2019-09-10 00:13:38 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:13:39 INFO [home.base_views:26] Parameters Receieved, PK - 1, Action - change
2019-09-10 00:13:43 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:13:53 INFO [tasks.views:176] Searching Tasks
2019-09-10 00:15:10 INFO [tasks.views:176] Searching Tasks
2019-09-10 00:15:10 INFO [tasks.views:202] Fetching All Tasks.
2019-09-10 00:17:25 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-10 00:17:46 ERROR [tasks.views:153] Task matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 123, in browse
    obj = Task.objects.get(key=task_key)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
tasks.models.Task.DoesNotExist: Task matching query does not exist.
2019-09-10 00:17:51 ERROR [tasks.views:153] Task matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 123, in browse
    obj = Task.objects.get(key=task_key)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
tasks.models.Task.DoesNotExist: Task matching query does not exist.
2019-09-10 00:18:01 INFO [tasks.views:176] Searching Tasks
2019-09-10 00:18:01 INFO [tasks.views:202] Fetching All Tasks.
2019-09-10 00:22:02 ERROR [tasks.views:155] Task matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 123, in browse
    obj = Task.objects.get(key=task_key)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
tasks.models.Task.DoesNotExist: Task matching query does not exist.
2019-09-10 00:22:15 INFO [tasks.views:178] Searching Tasks
2019-09-10 00:22:15 INFO [tasks.views:204] Fetching All Tasks.
2019-09-10 00:23:01 ERROR [tasks.views:155] Task matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 123, in browse
    obj = Task.objects.get(key=task_key)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
tasks.models.Task.DoesNotExist: Task matching query does not exist.
2019-09-10 00:23:23 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-10 00:23:36 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-10 00:25:37 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-10 00:26:06 ERROR [tasks.views:155] Task matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 123, in browse
    obj = Task.objects.get(key=task_key)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
tasks.models.Task.DoesNotExist: Task matching query does not exist.
2019-09-10 00:26:12 ERROR [tasks.views:155] Task matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 123, in browse
    obj = Task.objects.get(key=task_key)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
tasks.models.Task.DoesNotExist: Task matching query does not exist.
2019-09-10 00:28:37 INFO [tasks.views:181] Searching Tasks
2019-09-10 00:29:14 INFO [tasks.views:181] Searching Tasks
2019-09-10 00:29:14 INFO [tasks.views:207] Fetching All Tasks.
2019-09-10 00:29:37 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-10 00:29:45 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:29:45 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:29:48 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:29:50 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:29:54 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:30:02 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:30:03 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:30:05 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:30:09 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:30:11 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:30:13 INFO [home.base_views:26] Parameters Receieved, PK - 1, Action - change
2019-09-10 00:30:18 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:30:19 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:30:22 INFO [tasks.views:181] Searching Tasks
2019-09-10 00:30:22 INFO [tasks.views:207] Fetching All Tasks.
2019-09-10 00:30:29 INFO [tasks.views:181] Searching Tasks
2019-09-10 00:32:42 INFO [tasks.views:181] Searching Tasks
2019-09-10 00:32:42 INFO [tasks.views:207] Fetching All Tasks.
2019-09-10 00:33:07 INFO [tasks.views:181] Searching Tasks
2019-09-10 00:33:15 INFO [tasks.views:181] Searching Tasks
2019-09-10 00:33:15 INFO [tasks.views:207] Fetching All Tasks.
2019-09-10 00:33:22 INFO [tasks.views:181] Searching Tasks
2019-09-10 00:33:25 INFO [tasks.views:181] Searching Tasks
2019-09-10 00:33:25 ERROR [tasks.views:232] Cannot resolve keyword 'reporter' into field. Choices are: assignee, assignee_id, attachments, comments, created_at, created_by, created_by_id, dependent_task_object, description, due_date, id, key, modified_at, modified_by, modified_by_id, parent_task_object, priority, project, project_id, state, summary, tasktype, tasktype_id, watchers
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 195, in search
    queryset = self.get_filter_data(request, task_filter)
  File "/home/mmt555/GITProjects/tracker/tracker/tasks/views.py", line 73, in get_filter_data
    queryset = Task.objects.filter(**fields_pattern).values(*self.fields)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1190, in build_filter
    lookups, parts, reffed_expression = self.solve_lookup_type(arg)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1049, in solve_lookup_type
    _, field, _, lookup_parts = self.names_to_path(lookup_splitted, self.get_meta())
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/sql/query.py", line 1420, in names_to_path
    "Choices are: %s" % (name, ", ".join(available)))
django.core.exceptions.FieldError: Cannot resolve keyword 'reporter' into field. Choices are: assignee, assignee_id, attachments, comments, created_at, created_by, created_by_id, dependent_task_object, description, due_date, id, key, modified_at, modified_by, modified_by_id, parent_task_object, priority, project, project_id, state, summary, tasktype, tasktype_id, watchers
2019-09-10 00:33:38 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - add
2019-09-10 00:33:40 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:33:41 INFO [home.base_views:26] Parameters Receieved, PK - 2, Action - change
2019-09-10 00:33:50 INFO [home.base_views:75] Params Receieved - pk - 2, Action - change
2019-09-10 00:33:50 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 00:33:52 INFO [tasks.views:181] Searching Tasks
2019-09-10 00:34:34 INFO [tasks.views:181] Searching Tasks
2019-09-10 00:34:36 INFO [tasks.views:181] Searching Tasks
2019-09-10 00:34:39 INFO [tasks.views:181] Searching Tasks
2019-09-10 00:34:41 INFO [tasks.views:181] Searching Tasks
2019-09-10 00:34:43 INFO [tasks.views:181] Searching Tasks
2019-09-10 00:34:43 INFO [tasks.views:207] Fetching All Tasks.
2019-09-10 00:35:31 INFO [tasks.views:181] Searching Tasks
2019-09-10 00:35:46 INFO [tasks.views:181] Searching Tasks
2019-09-10 00:36:09 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-10 00:36:22 INFO [tasks.views:181] Searching Tasks
2019-09-10 00:36:22 INFO [tasks.views:207] Fetching All Tasks.
2019-09-10 00:36:54 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-10 22:30:17 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-10 22:30:25 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 22:30:26 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 22:30:27 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 22:30:28 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 22:30:30 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 22:30:31 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 22:30:32 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 22:30:33 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 22:30:34 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 22:30:35 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 22:30:36 INFO [home.base_views:26] Parameters Receieved, PK - None, Action - None
2019-09-10 22:30:40 INFO [tasks.views:181] Searching Tasks
2019-09-10 22:30:44 INFO [tasks.views:181] Searching Tasks
2019-09-10 22:30:46 INFO [tasks.views:181] Searching Tasks
2019-09-10 22:30:46 INFO [tasks.views:207] Fetching All Tasks.
2019-09-10 22:31:01 INFO [tasks.views:181] Searching Tasks
2019-09-10 22:31:10 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
2019-09-10 22:31:18 ERROR [home.views:32] User matching query does not exist.
Traceback (most recent call last):
  File "/home/mmt555/GITProjects/tracker/tracker/home/views.py", line 29, in _get_system_filters
    user = User.objects.get(username=username)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/mmt555/virtualenvs/tracker/lib/python3.6/site-packages/django/db/models/query.py", line 408, in get
    self.model._meta.object_name
accounts.models.User.DoesNotExist: User matching query does not exist.
